# Generated by Django 3.1.4 on 2020-12-31 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=300, unique=True, verbose_name='密码')),
                ('token', models.CharField(max_length=300, verbose_name='token')),
                ('realname', models.CharField(max_length=20, verbose_name='真实姓名')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('regtime', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
            ],
            options={
                'db_table': 'User',
                'ordering': ('user_id',),
            },
        ),
    ]
