# Generated by Django 3.1.4 on 2021-01-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StuInfo',
            fields=[
                ('stunum', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='学号')),
                ('stuname', models.CharField(max_length=20, unique=True, verbose_name='姓名')),
                ('stuphone', models.CharField(max_length=15, verbose_name='联系方式')),
                ('stubirth', models.DateTimeField(max_length=20, verbose_name='出生日期')),
                ('stusex', models.IntegerField(max_length=5, verbose_name='性别')),
                ('stuidcard', models.CharField(max_length=20, verbose_name='身份证')),
                ('stumajor', models.CharField(max_length=50, verbose_name='专业')),
                ('stufaculty', models.CharField(max_length=50, verbose_name='学院')),
                ('stuimg', models.CharField(max_length=200, null=True, verbose_name='照片')),
                ('stuin', models.DateTimeField(max_length=20, verbose_name='入学年份')),
                ('stuadress', models.CharField(max_length=200, null=True, verbose_name='住址')),
            ],
            options={
                'db_table': 'stuinfo',
                'ordering': ('stunum',),
            },
        ),
    ]
