# Generated by Django 3.1.4 on 2021-01-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuinfo',
            name='stuname',
            field=models.CharField(max_length=20, verbose_name='姓名'),
        ),
    ]
