# Generated by Django 3.1.4 on 2021-01-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stu', '0002_auto_20210101_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuinfo',
            name='stubirth',
            field=models.DateField(max_length=20, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='stuinfo',
            name='stuin',
            field=models.DateField(max_length=20, verbose_name='入学年份'),
        ),
    ]
