# Generated by Django 3.1.4 on 2021-01-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stu', '0003_auto_20210101_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuinfo',
            name='stusex',
            field=models.IntegerField(choices=[(1, '男'), (0, '女')], verbose_name='性别'),
        ),
    ]
